---
abstract: 'Install the WWW::Search modules for Czech antiquarian bookstores.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-WWW-Search-Antiquarian-Czech
no_index:
  directory:
    - inc
    - t
requires:
  WWW::Search::Antikvariat11CZ: 0.01
  WWW::Search::AntikvariatJudaicaCZ: 0.02
  WWW::Search::GalerieIlonkaCZ: 0.01
  WWW::Search::KacurCZ: 0.01
  WWW::Search::MelcerCZ: 0.01
  WWW::Search::ValentinskaCZ: 0.02
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-WWW-Search-Antiquarian-Czech
  homepage: https://github.com/tupinek/Task-WWW-Search-Antiquarian-Czech
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Task-WWW-Search-Antiquarian-Czech
version: '0.02'
